
INSERT INTO PersonEstateRelation (Person_ID ,Estate_ID )
VALUES (1,1);

INSERT INTO PersonEstateRelation(Person_ID ,Estate_ID )
VALUES (2,2);

INSERT INTO Contract (CONTRACT_NUMBER,DATE ,PLACE ,PE_ID)
VALUES (1231,NOW(),'ST petrisburg',1);

INSERT INTO Contract(CONTRACT_NUMBER,DATE ,PLACE ,PE_ID)
VALUES (1232,NOW(),'ST petrisburg',2);

INSERT INTO PurchaseContract (INSTALLMENTS, INTEREST_RATE , Contract_ID)
VALUES(1,12,1);

INSERT INTO TenancyContract(START_DATE,DURATION ,ADD_COSTS,Contract_ID )
VALUES (NOW(),2,20,2);
